/**
 * Builds the viewer, twice, from the same three files.
 *
 * `src/viewer/app` holds the page: markup, styles, and the script that draws everything.
 * What it does not hold is where the archives come from -- that is handed in when it
 * starts, so the same script serves both of these:
 *
 *   served  the page `mosaic serve` answers with, bundled into `src/api/app/page.ts` as a
 *           string, because the CLI ships as one executable with no directory to read
 *           from. It asks the server it came from.
 *
 *   static  a folder of files that needs no server at all, written to `examples/viewer`
 *           for github pages. It reads .tsr files beside itself and does the selection and
 *           the glTF conversion in the browser.
 *
 * three.js stays external in both: it comes from a CDN through the import map in the
 * markup, which is what keeps a fifty-megabyte dependency out of a page and out of an
 * executable.
 */
import * as esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const app = path.join(root, "src", "viewer", "app");
const repo = path.resolve(root, "..", "..");

const markup = fs.readFileSync(path.join(app, "index.html"), "utf-8");
const styles = fs.readFileSync(path.join(app, "app.css"), "utf-8");

if (!markup.includes("<!--STYLES-->") || !markup.includes("<!--SCRIPT-->")) {
    throw new Error("index.html has lost the marks the build fills in");
}

const KB = bytes => (bytes / 1024).toFixed(1) + " KB";

/** One entry point, bundled for a browser, as a string. */
async function bundle(entry) {
    const built = await esbuild.build({
        entryPoints: [path.join(app, entry)],
        bundle: true,
        format: "esm",
        platform: "browser",
        target: "es2022",
        // Resolved by the import map in the markup, from a CDN, at run time.
        external: ["three", "three/addons/*"],
        write: false,
        legalComments: "none",
        logLevel: "warning",
    });

    const [out] = built.outputFiles;
    if (!out) throw new Error(`${entry} produced nothing`);
    return out.text;
}

/** The markup with the styles and a script put into it. */
const assemble = (script, asFile) => markup
    .replace("<!--STYLES-->", "<style>\n" + styles.trimEnd() + "\n</style>")
    .replace("<!--SCRIPT-->", asFile
        ? '<script type="module" src="app.js"></script>'
        : '<script type="module">\n' + script.trimEnd() + "\n</script>");

// --- the served page --------------------------------------------------------
const servedScript = await bundle("boot-server.ts");
const served = assemble(servedScript, false);

/**
 * Written as a quoted string rather than a template.
 *
 * It used to be a String.raw, which meant no backtick and no `${` could appear anywhere in
 * a thousand lines of script -- a rule nothing enforced and several changes broke. A
 * JSON string has no such rule, and the page is generated now rather than written, so
 * nobody has to keep one.
 */
const generated = `// Generated by scripts/build-viewer.mjs from src/viewer/app. Do not edit.
//
// The viewer is three files over there -- index.html, app.css, app.js -- and this is them,
// bundled with the source that asks this server for its archives. Run "npm run build:viewer"
// after changing any of them.
//
// It is a string because the CLI ships as a single executable, where there is no directory
// to read a page out of.

/** The page \`mosaic serve\` puts at \`/\`. */
export const APP_PAGE = ${JSON.stringify(served)};
`;

const pageFile = path.join(root, "src", "api", "app", "page.ts");
fs.writeFileSync(pageFile, generated);
console.log("served page  " + KB(served.length) + "  ->  " + path.relative(repo, pageFile));

// --- the static app ---------------------------------------------------------
const staticScript = await bundle("boot-static.ts");
const into = path.join(repo, "examples", "viewer");
fs.mkdirSync(into, { recursive: true });

fs.writeFileSync(path.join(into, "index.html"), assemble(staticScript, true));
fs.writeFileSync(path.join(into, "app.js"), staticScript);

// Github Pages runs everything through Jekyll unless told not to, which eats files and
// folders whose names begin with an underscore.
fs.writeFileSync(path.join(into, ".nojekyll"), "");

console.log("static app   " + KB(staticScript.length) + " of script  ->  "
    + path.relative(repo, into));
